#!/bin/bash

# Install native apps
# Usage: `./Caskfile`

brew tap caskroom/cask
brew tap caskroom/versions

brew cask install dropbox 2> /dev/null
brew cask install google-chrome 2> /dev/null
brew cask install google-chrome-canary 2> /dev/null
brew cask install transmission 2> /dev/null
brew cask install atom 2> /dev/null
brew cask install adobe-creative-cloud 2> /dev/null
brew cask install cyberduck 2> /dev/null
brew cask install google-drive 2> /dev/null
brew cask install heroku-toolbelt 2> /dev/null
brew cask install skype 2> /dev/null
# brew cask install vmware-fusion> /dev/null
brew cask install appcleaner 2> /dev/null
brew cask install firefox 2> /dev/null
brew cask install adobe-reader 2> /dev/null
brew cask install gimp 2> /dev/null
brew cask install bettertouchtool 2> /dev/null
brew cask install caffeine 2> /dev/null
brew cask install charles 2> /dev/null
brew cask install Caskroom/cask/java 2> /dev/null
brew cask install gradle 2> /dev/null
brew cask install dockertoolbox 2> /dev/null
brew cask install calibre 2> /dev/null
brew cask install webstorm 2> /dev/null
brew cask install jet 2> /dev/null
brew cask install hipchat 2> /dev/null
brew cask install minikube 2> /dev/null
brew cask install cheatsheet 2> /dev/null
brew cask install kindle 2> /dev/null
brew cask install karabiner-elements> /dev/null
